# Generated by Django 5.1.3 on 2024-11-11 06:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='note',
            name='unique_note_slug',
        ),
        migrations.RemoveConstraint(
            model_name='notebook',
            name='unique_noteBook_slug',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='notebook',
            old_name='user',
            new_name='author',
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(fields=('author', 'slug'), name='unique_note_slug'),
        ),
        migrations.AddConstraint(
            model_name='notebook',
            constraint=models.UniqueConstraint(fields=('author', 'slug'), name='unique_noteBook_slug'),
        ),
    ]
